project/views/auth.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user
from flask_login import login_required

from project.forms import Login
from project.models import Users

auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    form = Login()
    if request.method == "GET":
        if current_user.is_active:
            return redirect(url_for("index.page"))
        return render_template("login.html", form=form)
    if form.validate_on_submit():
        user = Users.query.filter_by(name=form.name.data).first()
        login_user(user, remember=form.remember.data)
        return redirect(url_for("index.page"))
    return render_template("login.html", form=form)

@auth.route("/logout", methods=["GET"])
@login_required
def logout():
    flash("Successfully logged out")
    logout_user()
    return redirect(url_for("auth.login"))

project/views/index.py
import pandas as pd
from sqlalchemy.orm.scoping import scoped_session
import csv as csv_
from io import BytesIO
import zipfile
import tempfile
from flask import (
    Blueprint,
    redirect,
    request,
    render_template,
    flash,
    send_file,
    url_for,
)
from flask_login import login_required
from project.helpers.db_session import db_session
from project.models import (
    Users,
    Phone_Number,
    TextReply,
    Email,
    EmailReply,
    Template,
    Lead,
)
import math

index = Blueprint("index", __name__)


@index.route("/", methods=["GET", "POST"])
@login_required
def page():
    if request.method == "POST":
        f = request.files["file"]
        if f.filename != "":
            try:
                with db_session() as sess:
                    upload(pd.read_csv(f.stream), sess)
            except Exception as e:
                flash(f"e: {e}")
                raise
    return render_template("index.html")


def upload(df: pd.DataFrame, session: scoped_session):
    from project.models import Addresses, Lead

    fails = 0
    successes = 0
    for _, row in df.iterrows():
        try:
            d = row.to_dict()
            for k, v in d.items():
                if type(v) != str and math.isnan(v):
                    d[k] = None
            if not Addresses.query.filter_by(
                address=d["address"], city=d["city"], state=d["state"]
            ).first():
                address = Addresses(
                    address=d["address"],
                    city=d["city"],
                    state=d["state"],
                    zip=d["zip"],
                    owner_occupied=d["owner_occupied"],
                    property_type=d["property_type"],
                )
            # !bug this could be an issue if there are two different people with the same name in the database
            # !bug the way to fix it is to automatically skiptrace them
            lead = Lead.query.filter_by(
                first_name=d["first_name"], last_name=d["last_name"]
            ).first()
            if not lead:
                lead = Lead(
                    first_name=d["first_name"],
                    last_name=d["last_name"],
                )
                if d["phone_number"]:
                    lead.add_phone(d["phone_number"])
            lead.addresses.append(address)
            session.add(lead)
            successes += 1
        except ValueError:
            # TODO add logger and custom Exceptions
            fails += 1
            print(f"unable to add{row}")
    if successes > 0:
        flash(f"uploaded {successes} new addresses successfully.")
    else:
        flash("No new Addresses found within csv")
    if fails:
        # TODO remove after logger installed
        flash(f"{fails} were unable to be added due to unrecognized column names")


@index.route("/delete")
@login_required
def delete():
    with db_session() as sess:
        delete = Lead.query.all()
        for lead in delete:
            sess.delete(lead)
    return redirect(url_for("index.page"))


@index.route("/download")
@login_required
def dump_to_csv():

    dumps = {}
    models = [Users, Lead, Phone_Number, TextReply, Email, EmailReply, Template]
    for m in models:
        headers = [c.name for c in m.__mapper__.columns]
        for i, h in enumerate(headers):
            if h == "id":
                headers.pop(i)
        dumps[m.__name__] = {"type": m, "name": m.__name__, "headers": headers}
    folder = BytesIO()
    with zipfile.ZipFile(folder, "w") as zip:

        for _, model in dumps.items():
            with tempfile.SpooledTemporaryFile(mode="w") as dump:
                outcsv = csv_.writer(dump)
                outcsv.writerow([h for h in model["headers"]])
                [
                    outcsv.writerow(
                        [getattr(curr, column) for column in model["headers"]]
                    )
                    for curr in model["type"].query.all()
                ]

                dump.seek(0)
                data = zipfile.ZipInfo(f"{model['name']}.csv")
                data.compress_type = zipfile.ZIP_DEFLATED
                zip.writestr(data, dump.read())
    folder.seek(0)
    return send_file(
        folder, attachment_filename="Marketing_Concept_dumps.zip", as_attachment=True
    )

project/views/leads.py
from datetime import datetime
from typing import Tuple
import json
import os
import requests

from flask import Blueprint, request, redirect, url_for, render_template, flash, session
from flask_login import login_required
from flask_sqlalchemy import Pagination

from project.__init__ import db
from project.forms import LeadsForm, FilterForm, SkiptraceForm, LeadsForm
from project.helpers.db_session import db_session
from project.models import Addresses, db
from project.models import Lead

leads = Blueprint("leads", __name__)


@leads.route("/leads", methods=["POST", "GET"])
@login_required
def main():
    with db_session(autocommit=False) as sess:
        filter_form = FilterForm()
        leads_form = SkiptraceForm()
        leads_form = LeadsForm()
        leads_form.select_lead.choices = []
        leads_form.leads = []
        filter_form.comp_select.choices = [
            "address",
            "city",
            "zip",
            "owner_occupied",
            "property_type",
        ]


        if request.method == "POST":
            if filter_form.filter_submit.data:
                column = filter_form.comp_select.data
                data = filter_form.info.data
                rows = filter_form.length.data
                addresses = filter(column, data, rows)
                session["filtered"] = {"column": column, "data": data, "rows": rows}
                return render(addresses, filter_form, leads_form)
            if leads_form.skip_submit.data:
                skipped_int = 0
                success = 0
                final_msg = ""
                lead_tuples = []
                for string in leads_form.select_lead.data:
                    print(string)
                    string: str
                    string_list = string.split("_")
                    lead_id, address_id = string_list[0], string_list[1]
                    lead_tuples.append((lead_id, address_id))
                for tuple in lead_tuples:
                    lead = Lead.query.get(tuple[0])
                    #     # API call does not work without first name, OR if already have phone/emails
                    if not lead.first_name:
                        skipped_int += 1
                        final_msg += f'skipping "{lead.first_name} {lead.last_name}" due to lack of information<br>'
                        continue
                    if lead.mobile_phones or lead.emails:
                        skipped_int += 1
                        final_msg += f'skipping "{lead.first_name} {lead.last_name}" due to already having phone/email<br>'
                        continue
                    # if lead.last_trace is not None:
                    #     # TODO add option to bypass this
                    #     skipped_int += 1
                    #     final_msg += f'skipping "{lead.first_name} {lead.last_name}" due already being traced<br>'
                    #     continue
                    address = Addresses.query.get(tuple[1])
                    lead_dict = get_lead_dict(lead, address)
                    person_data = get_pf_api_data(lead_dict)
                    if person_data:
                        age, mobile_phones, emails = extract_info_from_person_data(
                            person_data
                        )
                        print(f'age: {age}')
                        print(f'mobile_phones: {mobile_phones}')
                        print(f'emails: {emails}')
                        lead.age = age
                        lead.add_phones(mobile_phones)
                        lead.add_emails(emails)
                        lead.last_trace = datetime.utcnow()
                    else:
                        final_msg += f'"{lead.first_name} {lead.last_name}" trace returned "No strong Matches<br>'
                        lead.last_trace = datetime.utcnow()
                    sess.add(lead)
                final_msg = (
                    final_msg[: -len("<br>")]
                    if final_msg != ""
                    else "all traces successful"
                )
                flash(final_msg)
                try:
                    sess.commit()
                    flash(
                        f"traced {success} leads successfully. skipped {skipped_int} traces."
                    )
                except Exception:
                    flash("There was an error inserting API data into database.")

            if leads_form.sms_submit.data:
                if leads_form.select_lead.data:
                    return redirect(url_for("apply.main", selected=json.dumps(leads_form.select_lead.data)))
                else:
                    return redirect(url_for("leads.main"))
        page = request.args.get("page", 1, type=int)
        if "filtered" in session.keys():
            addresses = filter(
                session["filtered"]["column"],
                session["filtered"]["data"],
                session["filtered"]["rows"],
            )
        else:
            addresses = (
                db.session.query(Addresses)
                .order_by(Addresses.id)
                .paginate(page=page, per_page=10)
            )
        for address in addresses.items:
            # This is where the selections from wtforms are paired with the database items
            setattr(address, "forms", [])
            address: Addresses
            for lead in address.leads:
                lead: Lead
                leads_form.select_lead.choices.append((f"{lead.id}_{address.id}"))
                # this is done this way because wtforms choices are kind of weird. 
                # I was looking for a better solution
                for choice in leads_form.select_lead:
                    pass
                address.forms.append((choice, lead))

        leads_form.select_address.choices = ["" for _ in range(addresses.per_page)]
        return render(addresses, filter_form, leads_form)


@leads.route("/leads/clear", methods=["GET"])
def clear():
    try:
        session.pop("filtered")
    except KeyError:
        pass
    return redirect(url_for("leads.main"))


def render(
    addresses: Pagination,
    filter_form: FilterForm,
    leads_form: LeadsForm,
):
    """render template function just used to be less verbose"""
    return render_template(
        "leads.html",
        addresses=addresses,
        filter_form=filter_form,
        leads_form=leads_form,
    )


def extract_info_from_person_data(person_data: dict) -> Tuple:
    """function that parses the incoming skiptrace data and returns relevant info"""
    age = (
        person_data["person"]["age"]
        if person_data["person"]["age"] != ""
        else "Unknown"
    )
    emails = [x["email"] for x in person_data["person"]["emails"]]
    # mobile_phones = [n for n in person_data["person"]["phones"]]
    mobile_phones = [n for n in _phone_data(person_data["person"]["phones"])]
        # for number in _phone_data(phone_group):
        #     mobile_phones.append(number)
    return age, mobile_phones, emails

def _phone_data(phone_data: list) -> str:
    """filter phone data and return numbers that are connected and were last reported after 2015"""
    print(f'phone_data: {phone_data}')
    for number in phone_data:
        is_mobile = number["type"] == "mobile"
        is_connected = number["isConnected"]
        is_current = int(number["lastReportedDate"].split("/")[2]) > 2015
        if is_mobile and is_connected and is_current:
            yield number["number"]

def get_pf_api_data(lead_dict: dict):
    """loads dict into http POST request and returns data"""
    payload = json.dumps(lead_dict)
    headers = {
        "Content-Type": "application/json",
        "galaxy-ap-name": os.environ.get("PEOPLE_API_NAME"),
        "galaxy-ap-password": os.environ.get("PEOPLE_API_PASS"),
        "galaxy-search-type": "DevAPIContactEnrich",
    }
    print(f'payload: {payload} || headers: {headers}')
    r = requests.post(
        "https://api.peoplefinderspro.com/contact/enrich", data=payload, headers=headers
    )
    response_body = r.text
    person_data: dict = json.loads(response_body)
    if not "person" in person_data.keys():
        return False
    person_data = r.json()
    return person_data


# def update_person_db(db, lead, age, mobile_phones, emails, session):
#     # Insert all phone numbers of lead into phone numbers table
#     for phone in mobile_phones:
#         p_exists = Phone_Number.query.filter_by(mobile_phone=phone).first()
#         if p_exists is None:
#             new = Phone_Number(mobile_phone=phone, lead_id=lead.id)
#             session.add(new)
#     for email in emails:
#         e_exists = Email.query.filter_by(email_address=email).first()
#         if e_exists is None:
#             new = Email(email_address=email, lead_id=lead.id)
#             session.add(new)
#     lead.age = age
#     lead.last_trace = datetime.utcnow()


def get_lead_dict(lead: Lead, address: Addresses ):
    """formats information for the skiptrace payload"""
    lead_dict = {
        "FirstName": lead.first_name,
        "LastName": lead.last_name,
        "Address": {
            "addressLine1": address.address,
            "addressLine2": f"{address.city}, {address.state}",
        },
    }
    return lead_dict


def filter(category: str, query_string: str, rows: int) -> Pagination:
    page = request.args.get("page", 1, type=int)
    addresses: Pagination = (
        db.session.query(Addresses)
        .filter(getattr(Addresses, category).like(f"%{query_string}%"))
        .paginate(page=page, per_page=rows)
    )
    return addresses

project/views/replies.py
from flask import Blueprint, render_template
from flask_login import login_required
import pytz
from project.models import Phone_Number, TextReply, Lead

replies = Blueprint("replies", __name__)

# TODO switch to addresses
# TODO add pagination. this will eventually crash if it gets too large
@replies.route("/replies", methods=["GET", "POST"])
@login_required
def main():
    _replies = TextReply.query.all()
    replies = []
    for r in _replies:
        num = Phone_Number.query.get(r.phone_id)
        lead = Lead.query.get(num.lead_id)
        replies.append(
            {
                "id": r.id,
                "message": r.message,
                "first_name": lead.first_name,
                "last_name": lead.last_name,
                "mls_status": lead.mls_status,
                "template_sent": lead.template_sent,
                "number": num.mobile_phone,
                "date": convert_date(r.contact_time),
                "time": convert_time(r.contact_time),
            }
        )
    return render_template("replies.html", replies=replies)


def convert_date(time):
    est = pytz.timezone("US/Eastern")
    fmt = "%m-%d-%Y"
    return time.astimezone(est).strftime(fmt)


def convert_time(time):
    est = pytz.timezone("US/Eastern")
    fmt = "%I:%M %p"
    return time.astimezone(est).strftime(fmt)

project/templates/_formhelpers.html
{% macro render_field(
field,
cls_er="errors",
check=false
) %}

{% if field.type == "SubmitField" or field.type == "HiddenField" %}
{{ field(**kwargs)|safe }}
{% elif check %}
{{ field(**kwargs)|safe }}
{{ field.label }}
{% else %}
{{ field.label }}
{{ field(**kwargs)|safe }}
{% endif %}

{% if field.errors %}
<ul class="{{cls_er}}">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endmacro %}

project/templates/admin.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}

{% if replies %}
    {% for reply in replies %}
        {{ reply }}
    {% endfor %}
{% endif %}

{% endblock %}

project/templates/apply_confirm.html
f{% extends 'base.html' %}

{% block head %}

{% endblock %}


{% block body %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const FNAME = "|First_Name|";
        const LNAME = "|Last_Name|";
        const AGE = "|Age|";
        const ADDRESS = "|Address|";
        const CITY = "|City|";
        const STATE = "|State|";
        const ZIP = "|zip|";
        const message = document.querySelector("p[data-flag='tmess']");
        const template = message.innerHTML;
        let new_ = template.replace(FNAME, '{{ example.first_name }}')
            .replace(LNAME, '{{ example.last_name }}')
            .replace(AGE, '{{ example.age }}')
            .replace(ADDRESS, '{{ example.address }}')
            .replace(CITY, '{{ example.city }}')
            .replace(STATE, '{{ example.state }}')
            .replace(ZIP, '{{ example.zip }}');
        message.innerHTML = new_;
    });
</script>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div style="display: flex; flex-direction: column;">
    <h2>
        {{template.name}}
    </h2>
    <p>
        {{template.message}}
    </p>
</div>
<div style="display: flex; flex-direction: column; border: solid">
    <h2>
        Example
    </h2>
    <p data-flag="tmess">
        {{template.message}}
    </p>
</div>
<form method="POST" style="display: flex; flex-direction: column;">
    <h2>Use Template: "{{template.name}}" to send {{amount}} messages?</h2>
    {{form_confirm.confirm_submit}}
</form>
{% endblock %}

project/templates/apply_template.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<script src="{{ url_for('static', filename='js/apply.js') }}"></script>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<form method="POST">
    <h2>Choose your SMS template</h2>
{% for tem in templates %}
    <div>
        <input type="checkbox" name="temp" value="{{tem.id}}">
        <h3>{{tem.name}}</h3>
        <p>{{tem.message}}</p>
    </div>
{% endfor %}<div style="display: flex; flex-direction: column;">
    <label for="sms_submit">Apply Template to {{amount}} Leads</label>
    <input id="sms_submit" type="submit" value="Choose">
</div>
</form>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Marketing Concept</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block body %}{%  endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

project/templates/flash.html
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

project/templates/index.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
{% include 'flash.html' %}

<br><br><br><br><br><br><br>
<h1 style="text-align: center;">Automated Lead Generator and Lead Qualifier</h1>

<div style="text-align: center;">
  <br>
  <h4>Upload your CSV file to the Leads Database</h4>
  <form method="POST" enctype="multipart/form-data">
    <br><br>
    <div class="mb-4" style="padding-left: 25%; padding-right: 25%;">
      <input type="file" name="file" class="form-control" id="formFileMultiple" multiple>
    </div>
    <div>
      <input class="btn btn-outline-secondary " type="submit" value="Submit">
    </div>
  </form>
</div>

<a href="{{url_for('index.dump_to_csv')}}" target="_blank"><button type="button" class="btn btn-secondary btn-lg">Download database as csv</button></a>
<a href="{{url_for('index.delete')}}" target="_blank"><button type="button" class="btn btn-secondary btn-lg">Delete</button></a>

{% endblock %}

project/templates/leads.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}



<script src="{{ url_for('static', filename='js/leads.js') }}"></script>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<br>
<h1 style="text-align:center">Lead Store</h1><br>
{% if addresses %}

<!-- filter table dropdown  DYLAN ADDED-->

<!-- <form class="form-inline" method="POST">

    <div class="form-group">
        {{ filter_form.comp_select.label }}
        <div class="input-group">
            {{ filter_form.comp_select (class="selectpicker form-control") }}
        </div>
        <div class="form-group">
            {{ filter_form.info.label }}
            {{ filter_form.info (class="form-control", id="exampleFormControlInput1", placeholder="name/city/zip") }}
        </div>
        <div class="form-group">
            {{ filter_form.length.label }}
            {{ filter_form.length (class="form-control", value="20") }}
        </div>
        {{ filter_form.filter_submit (class="btn btn-secondary", style="margin-top: 10px;") }}
        <a class="btn btn-secondary" , style="margin-top: 10px;" , href="{{url_for('leads.clear')}}">Clear Filter</a>
    </div>
</form>
<span style="float: right;">Select All <input class="form-check-input" type="checkbox"
        data-flag="select-all" /></span><br /> -->


<div class="table-responsive">
    <form action="" method='POST'>
        {% for option in leads_form.select_address %}
        {% set i = loop.index - 1 %}
        <div class="address-container">
            <table class="table table-striped">
                <tr class="mc_header address_header">
                    <th>{{leads_form.select_address.label}}</th>
                    <th>address</th>
                    <th>city</th>
                    <th>state</th>
                    <th>zip</th>
                    <th>owner occupied</th>
                    <th>property type</th>
                    <th>id</th>
                </tr>
                <tr>
                    <td>{{option (class="form-check-input", data_click="address", data_pair=addresses.items[i].id, value=addresses.items[i].id)}}
                    </td>
                    <td>{{addresses.items[i].address}}</td>
                    <td>{{addresses.items[i].city}}</td>
                    <td>{{addresses.items[i].state}}</td>
                    <td>{{addresses.items[i].zip}}</td>
                    <td>{{addresses.items[i].owner_occupied}}</td>
                    <td>{{addresses.items[i].property_type}}</td>
                    <td>{{addresses.items[i].id}}</td>
                </tr>
            </table>
            {% if addresses.items[i].leads %}
            <table class="table table-striped lead_table">
                <tr class="lead_header">
                    <th>{{leads_form.select_lead.label}}</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone numbers</th>
                    <th>contacted</th>
                    <th>contact time</th>
                    <th>Trace Date</th>
                    <th>Last Trace</th>
                    <th>Template Sent</th>
                    <th>Response</th>
                    <th>Motivation Level</th>
                    <th>Age</th>
                    <th>id</th>
                </tr>
                {% for tuple in addresses.items[i].forms %}
                {% set option = tuple[0] %}
                {% set lead = tuple[1] %}
                <tr>
                    <td>{{option (class="form-check-input", data_click="lead", data_pair=addresses.items[i].id)}}
                    </td>
                    <td>{{lead.first_name}}</td>
                    <td>{{lead.last_name}}</td>
                    <td>
                        {% if lead.mobile_phones %}
                        {% for number in lead.mobile_phones %}
                        {{number.mobile_phone}},
                        {% endfor %}
                        {% else %}
                        None
                        {% endif %}
                    </td>
                    <td>{{lead.contacted}}</td>
                    <td>{{lead.contact_time}}</td>
                    <td>{{lead.trace_date}}</td>
                    <td>{{lead.last_trace}}</td>
                    <td>{{lead.template_sent}}</td>
                    <td>{{lead.response}}</td>
                    <td>{{lead.motivation_level}}</td>
                    <td>{{lead.age}}</td>
                    <td>{{lead.id}}</td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
        {% endfor %}
        {{ leads_form.sms_submit (class="btn btn-secondary", style="margin-bottom: 10px;",
        data_flag="template_button")}}
        {{ leads_form.skip_submit (class="btn btn-secondary", style="margin-bottom: 10px;") }}
        <p>Texts Remaining: {{current_user.texts_left}}</p>
    </form>
</div>

<!-- Pagination Links-->
<div class="text-right" style="float: right; margin-top: 11px;">
    <a href="{{ url_for('leads.main', page=addresses.prev_num) }}" class="btn btn-outline-dark 
       {% if addresses.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
    <!-- Loop through the number of pages to display a link for each-->
    {% for page_num in addresses.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    <!-- Check for the active page and set the link to "Active"-->
    {% if addresses.page == page_num %}
    <a href="{{ url_for('leads.main', page=page_num) }}" class="btn btn-dark">
        {{ page_num }}
    </a>
    {% else %}
    <a href="{{ url_for('leads.main', page=page_num) }}" class="btn btn-outline-dark">
        {{ page_num }}
    </a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
    <a href="{{ url_for('leads.main', page=addresses.next_num) }}" class="btn btn-outline-dark 
       {% if addresses.page == addresses.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p class="text-right mt-3">
    Showing page {{ addresses.page }} of {{ addresses.pages }}
</p>
{% endif %}

{% endblock %}

project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('index.page') }}">Marketing Concept</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.index') }}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('leads.main') }}">Leads</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('templates.main') }}">Templates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('replies.main') }}">Replies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li> -->
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>